# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Gendiff CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        pip install poetry
        make install
    - name: Lint with flake8
      run: |
        make lint
    - name: Test with pytest
      run: |
        make test
    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v3.0.0
      env: 
        CODECLIMATE_REPO_TOKEN: ed3368785be593ed7ba2b0d57705ee88bca01b11b0426ccf5e61ed324f1abaef
        CC_TEST_REPORTER_ID: 8792c8e14d089c0545ba202bb29bd6b0e055452fb65c2e3976b24d465d456b42
      with:
        coverageCommand: make test-cov
        debug: true
